import type { Metadata } from "next";
import "./globals.css";
import { dmSans, roxter, streach, syne } from "@/utils/fonts";
import CTAButton from "@/components/CTAButton";
import SmoothScroll from "@/components/SmoothScroll";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import {Toaster} from "react-hot-toast";
const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "SkyBlue - Avation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)} suppressHydrationWarning>
      <body
        className={`${dmSans.className} ${streach.variable} ${roxter.variable} ${syne.variable} antialiased relative`}
      >
          {children}
      </body>
    </html>
  );
}
